name: random_coffee_repository
description: Repository responsible for retrieving random coffee images.
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.9.2
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  http_client:
    path: ../http_client
  vgcfp_core:
    path: ../vgcfp_core

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
