name: http_client
description: HTTP client abstractions for the Very Good Coffee app.
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.9.2
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  vgcfp_core:
    path: ../vgcfp_core

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0
