name: connectivity_helper
description: Connectivity utilities for Very Good Coffee projects.
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.9.2
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  connectivity_plus: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0
